import { mkdir, rm } from 'node:fs/promises';
import { main } from './research.js';
import { fixtureRows } from '../tests/fixtures.js';
import { writeJsonl } from '../src/io.js';
import { spawnSync } from 'node:child_process';
const root = 'data/smoke';
await rm(root, { recursive: true, force: true }); await mkdir(root, { recursive: true });
await writeJsonl(`${root}/fixture.jsonl`, fixtureRows());
await main(['prepare', '--input', `${root}/fixture.jsonl`, '--out', `${root}/prepared`]);
const common = ['--data', `${root}/prepared/examples.jsonl`, '--manifest', `${root}/prepared/manifest.json`];
await main(['fit-baseline', ...common, '--method', 'tfidf', '--out', `${root}/tfidf.json`]);
await main(['fit-baseline', ...common, '--method', 'prior', '--out', `${root}/prior.json`]);
for (const method of ['tfidf', 'prior']) await main(['run', ...common, '--method', method, '--model', `${root}/${method}.json`, '--execute', '--out', `${root}/${method}-dev.json`]);
const comparison = spawnSync(process.execPath, ['scripts/compare.js', `${root}/tfidf-dev.json`, `${root}/prior-dev.json`, '--out', `${root}/comparison.json`], { stdio: 'inherit' });
if (comparison.status !== 0) throw new Error('Grouped development comparison failed');
await main(['run', ...common, '--split', 'calibration', '--method', 'tfidf', '--model', `${root}/tfidf.json`, '--execute', '--out', `${root}/calibration-run.json`]);
await main(['calibrate', ...common, '--run', `${root}/calibration-run.json`, '--out', `${root}/calibration.json`]);
await main(['freeze', ...common, '--calibration', `${root}/calibration.json`, '--out', `${root}/freeze.json`]);
await main(['run', ...common, '--split', 'test', '--freeze', `${root}/freeze.json`, '--open-test', '--execute', '--out', `${root}/test-run.json`]);
await main(['evaluate', ...common, '--split', 'test', '--freeze', `${root}/freeze.json`, '--open-test', '--run', `${root}/test-run.json`, '--out', `${root}/report.json`, '--replicates', '100']);
await main(['report', '--report', `${root}/report.json`, '--out', `${root}/report.md`]);
console.log('Synthetic end-to-end pipeline passed. No provider calls. These are not detection research results.');
